// ============================================================
// HUNDRED BLOCK DASH — the map module.
//
// A linear board: `player.pos` is a NUMBER, the layout is generated from the
// chosen length (50 / 75 / 100) rather than declared, and the run ends at a
// finish line instead of on a round count. It carries no graph, no pools and no
// junctions, and every consumer must ask `ActiveMap.isLinear()` before reaching
// for one — which is exactly what the feature flags below are for.
//
// The board itself is still generated by BoardSetup.generateBoard() from
// GameConfig.buildHbdConfig(), because its layout is a function of the length
// the player picked and cannot be a static table.
// ============================================================

export default {
    id:      'hundred_block_dash',
    kind:    'linear',
    start:   0,
    graph:   null,
    pools:   null,
    ordered: null,          // ActiveMap.ordered() synthesises 0..finish
    junctions:   new Set(),
    branches:    {},
    hubKey:      null,
    regionKeys:  [],        // realms are positional, not named regions
    regionNames: {},
    botBias: {},
    layout:  { kind: 'hbd_curve' },
    gateNode: null,         // the Rift's position is computed from the length
    gateThreshold: 20,
    mapLabels: { title: 'THE ROAD',  start: 'START', middle: 'REALMS',      end: '👑 CROWN' },
    features: {
        bounties:      false,
        buddies:       false,
        duels:         false,
        gate:          true,   // The Rift
        hqBonus:       false,
        circuitBonus:  false,
        stars:         false,
        roundLimit:    false,  // ends when someone reaches the Crown
        finishBonus:   true,
        realms:        true,   // per-space biome re-skinning
        routeChoice:   false,
    },
};
