#!/usr/bin/env node
// ============================================================
// APPLY LAYOUT — a saved map-editor layout into the game
//
// Takes a layout as JSON (what the editor saves: { map, items: [...] }),
// checks every field, and writes src/config/layouts/<map>.js, which the
// game loads. Layout data arrives from a web page, so nothing in it is
// trusted: unknown maps and models are refused, numbers must be finite and
// inside the board, and the output is written as a JSON literal, never as
// code taken from the input.
//
// usage: node scripts/apply-layout.js <layout.json>
//        (qa/exportlayout.js calls writeLayout() directly)
// ============================================================
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MAPS = { city_circuit: 138 };            // map → how far from the centre an item may stand

// The model keys CityKit.MODELS defines, read from its source so the two
// cannot disagree.
function modelKeys() {
    const src = fs.readFileSync(path.join(ROOT, 'src/engine/CityKit.js'), 'utf8');
    const block = src.slice(src.indexOf('export const MODELS = {'));
    const body = block.slice(0, block.indexOf('\n};'));
    return new Set([...body.matchAll(/^\s{4}'?([a-z][a-z-]*)'?:\s*\{/gm)].map(m => m[1]));
}

function fail(msg) { throw new Error('layout rejected: ' + msg); }
const num = (v, what) => { if (typeof v !== 'number' || !Number.isFinite(v)) fail(`${what} is not a number`); return v; };

function validate(layout) {
    if (!layout || typeof layout !== 'object') fail('not an object');
    const reach = MAPS[layout.map];
    if (!reach) fail(`unknown map "${layout.map}"`);
    if (!Array.isArray(layout.items)) fail('items is not a list');
    if (layout.items.length > 600) fail(`${layout.items.length} items (limit 600)`);
    const known = modelKeys();
    const items = layout.items.map((it, i) => {
        const at = `item ${i}`;
        if (!it || typeof it !== 'object') fail(`${at} is not an object`);
        if (!known.has(it.model)) fail(`${at}: unknown model "${it.model}"`);
        const x = num(it.x, `${at}.x`), z = num(it.z, `${at}.z`);
        if (Math.hypot(x, z) > reach) fail(`${at} stands off the board (${x.toFixed(1)}, ${z.toFixed(1)})`);
        let rotY = num(it.rotY ?? 0, `${at}.rotY`);
        rotY = Math.atan2(Math.sin(rotY), Math.cos(rotY));
        const scale = num(it.scale ?? 1, `${at}.scale`);
        if (scale < 0.5 || scale > 2) fail(`${at}.scale ${scale} outside 0.5–2`);
        const seed = num(it.seed ?? 0, `${at}.seed`);
        if (!Number.isInteger(seed) || seed < 0 || seed > 99) fail(`${at}.seed ${seed} is not 0–99`);
        const r3 = n => Math.round(n * 1000) / 1000;
        return { model: it.model, seed, hq: it.hq === true, x: r3(x), z: r3(z), rotY: r3(rotY), scale: r3(scale) };
    });
    const note = typeof layout.note === 'string' ? layout.note.slice(0, 300) : '';
    const savedAt = typeof layout.savedAt === 'string' && !isNaN(Date.parse(layout.savedAt)) ? layout.savedAt : new Date().toISOString();
    return { map: layout.map, version: 1, savedAt, note, items };
}

function writeLayout(layout) {
    const clean = validate(layout);
    const file = path.join(ROOT, 'src/config/layouts', clean.map + '.js');
    const body = JSON.stringify(clean, null, 1)
        .replace(/\n {2,}/g, ' ').replace(/\{ "model"/g, '\n  { "model"');    // one item per line
    fs.writeFileSync(file,
        `// GENERATED by scripts/apply-layout.js from a map-editor layout — don't hand-edit.\n` +
        `// ${clean.items.length} items · saved ${clean.savedAt}${clean.note ? ' · ' + clean.note.replace(/[\r\n]+/g, ' ') : ''}\n` +
        `export default ${body};\n`);
    return { file, count: clean.items.length };
}

module.exports = { validate, writeLayout };

if (require.main === module) {
    const src = process.argv[2];
    if (!src) { console.error('usage: node scripts/apply-layout.js <layout.json>'); process.exit(2); }
    try {
        const r = writeLayout(JSON.parse(fs.readFileSync(src, 'utf8')));
        console.log(`wrote ${path.relative(ROOT, r.file)} (${r.count} items)`);
    } catch (e) { console.error(e.message); process.exit(1); }
}
